trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  version: 1.0.0-$(Build.BuildId)

steps:
# Step 1: Use .NET SDK version 8.x.x
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

# Step 2: Restore NuGet dependencies
- script: dotnet restore ClassLibraryProjects/ClassLibraryProjects.sln
  displayName: 'Restore Dependencies'

# Step 3: Build the project
- script: dotnet build ClassLibraryProjects/ClassLibraryProjects.sln --configuration Release
  displayName: 'Build Solution'

# Step 4: Pack the solution into a NuGet package
- script: dotnet pack ClassLibraryProjects/ClassLibraryProjects.sln --configuration Release --output $(Build.ArtifactStagingDirectory) /p:PackageVersion=$(version)
  displayName: 'Pack NuGet'

# Step 5: Push the NuGet package to Azure Artifacts Feed
- task: NuGetCommand@2
  inputs:
    command: push
    publishVstsFeed: 'Feed1'  # Ensure this is the correct Azure Artifacts feed name
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'


