trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet build --configuration Release
  displayName: 'Build'

- script: dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack NuGet'

- task: NuGetCommand@2
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishVstsFeed: '<your-feed-id>'  # You’ll replace this
